#!/usr/bin/env python3
"""Emit 2D rows for Spirits tab batch 1 (Composio UPDATE_VALUES_BATCH)."""
from __future__ import annotations

import json
from pathlib import Path

BASE = Path(__file__).resolve().parent
OUT = BASE / "spirit-research-tracker-batch-1-sheet.json"

HEADERS = [
    "SKU", "Brand", "Product Name", "Expression", "Spirit Type", "Style", "Origin",
    "Tier", "Journey Level", "Journey Rank", "Proof", "ABV %", "Mash / Grain Bill",
    "Flavor Family", "Occasion", "Pairing Affinity (Cigar)", "Flavor Notes", "Notes",
    "Best For", "Avoid If", "Why Recommend", "Recommendation Confidence",
    "Source Confidence", "MSRP USD", "Catalog Line", "Member Blurb", "Awards Summary",
    "Image URL", "Article Source", "Sterlon",
]

ROWS = [
    {
        "sku": "SPI-TRK-BT-BUFFALO",
        "brand": "Buffalo Trace",
        "name": "Buffalo Trace Kentucky Straight Bourbon",
        "expr": "Standard",
        "type": "Bourbon",
        "style": "Kentucky Straight Bourbon",
        "origin": "Kentucky",
        "tier": 3,
        "journey": "novice",
        "rank": 2,
        "proof": 90,
        "mash": "Corn, rye, malted barley (BT mash bill #1)",
        "family": "Vanilla & caramel",
        "occasion": "Everyday pour",
        "pairing": "Connecticut / mild cigar",
        "notes": "vanilla, mint, molasses, brown sugar, spice, oak, toffee, dark fruit, anise",
        "research": "Buffalo Trace Distillery official flagship; 90 proof, mash bill #1.",
        "source": "Manufacturer official",
        "article": "https://www.buffalotracedistillery.com/our-brands/buffalo-trace/buffalo-trace-bourbon/",
        "best": "Bourbon beginner, first pour, user wants approachable sweetness without heat.",
        "avoid": "User wants peat, high-proof spice bomb, or allocated wheated collector only.",
        "why": "Recommend when the member is new to bourbon or asks what to start with — vanilla, caramel, gentle oak.",
        "msrp": 28,
        "blurb": "Buffalo Trace — vanilla, mint, and molasses over brown sugar, toffee, and dark fruit. The distillery's official teaching pour for bourbon newcomers.",
    },
    {
        "sku": "SPI-TRK-WOODFORD",
        "brand": "Woodford Reserve",
        "name": "Woodford Reserve Kentucky Straight Bourbon",
        "expr": "Standard",
        "type": "Bourbon",
        "style": "Kentucky Straight Bourbon",
        "origin": "Kentucky",
        "tier": 4,
        "journey": "intermediate",
        "rank": 5,
        "proof": 90.4,
        "mash": "Corn, rye, malted barley (high rye accent)",
        "family": "Cocoa & spice",
        "occasion": "After dinner",
        "pairing": "Medium-body cigar",
        "notes": "dried fruit, mint, orange, cocoa, vanilla, tobacco spice, citrus, cinnamon, toffee, caramel, chocolate",
        "research": "Woodford Reserve official: 90.4 proof pot-still bourbon.",
        "source": "Manufacturer official",
        "article": "https://www.woodfordreserve.com/whiskey/straight-bourbon-whiskey/",
        "best": "Member wants polished bourbon between entry and allocated, medium cigar night.",
        "avoid": "User needs lowest price point or maximum peat/smoke.",
        "why": "Recommend for cocoa-oak balance beside a medium-bodied cigar — step up from Buffalo Trace without collector pricing.",
        "msrp": 38,
        "blurb": "Woodford Reserve — dried fruit, orange, and cocoa over cinnamon, toffee, and chocolate. Official pot-still profile built for a medium cigar.",
    },
    {
        "sku": "SPI-TRK-OF-1920",
        "brand": "Old Forester",
        "name": "Old Forester 1920 Prohibition Style",
        "expr": "1920 Prohibition Style",
        "type": "Bourbon",
        "style": "Kentucky Straight Bourbon",
        "origin": "Kentucky",
        "tier": 5,
        "journey": "intermediate",
        "rank": 6,
        "proof": 115,
        "mash": "Corn, rye, malted barley (Whiskey Row series)",
        "family": "Dark fruit & chocolate",
        "occasion": "After dinner",
        "pairing": "Maduro / stronger cigar",
        "notes": "cherry preserves, caramel, dark chocolate, maple syrup, spiced nuts, malt, nougat, rye spice, cedar, toasted coconut, charred marshmallow, oak spice",
        "research": "Old Forester official Whiskey Row; 115 proof Prohibition-style.",
        "source": "Manufacturer official",
        "article": "https://www.oldforester.com/bourbons/1920-prohibition-style/",
        "best": "Experienced bourbon drinker, maduro pairing, user wants proof and dark fruit.",
        "avoid": "Beginner, empty stomach, or user wants mild Connecticut-only pairing.",
        "why": "Recommend when the member wants a stronger bourbon for maduro — dark cherry, chocolate, and controlled heat.",
        "msrp": 65,
        "blurb": "Old Forester 1920 — cherry preserves and caramel over dark chocolate, maple, and toasted coconut at 115 proof. Distillery-official maduro partner.",
    },
    {
        "sku": "SPI-TRK-EAGLE-RARE",
        "brand": "Eagle Rare",
        "name": "Eagle Rare Kentucky Straight Bourbon",
        "expr": "10 Year",
        "type": "Bourbon",
        "style": "Kentucky Straight Bourbon",
        "origin": "Kentucky",
        "tier": 4,
        "journey": "intermediate",
        "rank": 4,
        "proof": 90,
        "mash": "Corn, rye, malted barley (BT mash bill)",
        "family": "Elegant oak",
        "occasion": "Relaxed evening",
        "pairing": "Corojo / medium-full cigar",
        "notes": "toffee, orange peel, herbs, honey, leather, oak, candied almonds, cocoa",
        "research": "Buffalo Trace Distillery official Eagle Rare 10 Year; 90 proof, mash bill #1.",
        "source": "Manufacturer official",
        "article": "https://www.buffalotracedistillery.com/our-brands/eagle-rare/eagle-rare-10/",
        "best": "Member wants refined bourbon without Pappy pricing, citrus-leather cigar pairing.",
        "avoid": "User demands cask-strength only or Islay smoke.",
        "why": "Recommend when the member wants elegant bourbon — leather, orange peel, and polished oak.",
        "msrp": 35,
        "blurb": "Eagle Rare 10 — toffee, orange peel, and leather over candied almonds and cocoa. Official BT ten-year profile without collector hype.",
    },
    {
        "sku": "SPI-TRK-WP-10",
        "brand": "WhistlePig",
        "name": "WhistlePig 10 Year",
        "expr": "10 Year",
        "type": "Rye",
        "style": "Straight rye whiskey",
        "origin": "Shoreham, Vermont",
        "tier": 5,
        "journey": "intermediate",
        "rank": 7,
        "proof": 100,
        "mash": "High-rye whiskey (Canadian distillate; bottled in Vermont)",
        "family": "Rye spice",
        "occasion": "After dinner",
        "pairing": "Peppery / spicy cigar",
        "notes": "allspice, orange peel, anise, oak, char, caramel, vanilla, rye spice, mint, butterscotch",
        "research": "WhistlePig official 10 Year Small Batch Rye; 100 proof.",
        "source": "Manufacturer official",
        "article": "https://www.whistlepigwhiskey.com/whiskeys/10-year",
        "best": "User asks for rye, spice-forward cigar, or bourbon drinker ready for rye.",
        "avoid": "User dislikes spice heat or wants unpeated Scotch only.",
        "why": "Recommend when the member wants to learn rye — pepper and mint over oak without losing body.",
        "msrp": 85,
        "blurb": "WhistlePig 10 — allspice and orange peel over caramel, rye spice, and mint with a butterscotch finish. Brand-official 100-proof rye lesson.",
    },
    {
        "sku": "SPI-TRK-SAZERAC-RYE",
        "brand": "Sazerac",
        "name": "Sazerac Rye",
        "expr": "Standard",
        "type": "Rye",
        "style": "Kentucky Straight Rye",
        "origin": "Kentucky",
        "tier": 3,
        "journey": "novice",
        "rank": 3,
        "proof": 90,
        "mash": "Rye-forward (Sazerac mash)",
        "family": "Spice & citrus",
        "occasion": "Cocktail / neat",
        "pairing": "Medium cigar",
        "notes": "clove, vanilla, anise, pepper, candied spice, citrus, licorice",
        "research": "Sazerac Company official; 90 proof Kentucky straight rye.",
        "source": "Manufacturer official",
        "article": "http://www.sazerac.com/our-brands/sazerac-rye-whiskey.html",
        "best": "Rye curious beginner, Old Fashioned/Sazerac order, budget-friendly rye.",
        "avoid": "User wants 100+ proof or heavy peat.",
        "why": "Recommend as the approachable rye entry — clove, citrus, and licorice without WhistlePig intensity.",
        "msrp": 32,
        "blurb": "Sazerac Rye — clove, vanilla, and anise over pepper, citrus, and licorice. Distillery-official rye for the namesake cocktail or a neat pour.",
    },
    {
        "sku": "SPI-TRK-MACALLAN-12",
        "brand": "The Macallan",
        "name": "The Macallan 12 Year Sherry Oak",
        "expr": "12 Year Sherry Oak",
        "type": "Scotch",
        "style": "Single malt Scotch",
        "origin": "Speyside, Scotland",
        "tier": 6,
        "journey": "advanced",
        "rank": 12,
        "proof": 86,
        "mash": "100% malted barley",
        "family": "Sherry & fruit",
        "occasion": "Celebration",
        "pairing": "Medium-full / maduro cigar",
        "notes": "sherry, dried fruit, chocolate, orange, ginger, oak",
        "research": "Mandatory for luxury perception; sherry-cask Speyside reference.",
        "best": "Member wants recognizable luxury Scotch, sherry sweetness, special occasion.",
        "avoid": "User wants peat smoke or lowest price Scotch.",
        "why": "Recommend when luxury Scotch perception matters — sherry, dried fruit, and chocolate beside a premium cigar.",
        "msrp": 70,
        "blurb": "Macallan 12 Sherry Oak — the luxury Scotch name everyone recognizes. Dried fruit, chocolate, and sherried depth without peat.",
    },
    {
        "sku": "SPI-TRK-LAG-16",
        "brand": "Lagavulin",
        "name": "Lagavulin 16 Year",
        "expr": "16 Year",
        "type": "Scotch",
        "style": "Single malt Scotch",
        "origin": "Islay, Scotland",
        "tier": 6,
        "journey": "advanced",
        "rank": 13,
        "proof": 86,
        "mash": "100% malted barley",
        "family": "Peat & smoke",
        "occasion": "After dinner",
        "pairing": "Full-bodied / maduro cigar",
        "notes": "campfire, sea salt, smoke, iodine, dark fruit, oak",
        "research": "Teaches peat and smoke; Islay benchmark for lounge education.",
        "best": "Member asks for smoky Scotch, peat, or bold cigar needs maritime smoke.",
        "avoid": "Peat-averse beginner or user wants light Speyside only.",
        "why": "Recommend when the member wants to understand peat — campfire, sea salt, and smoke done with balance.",
        "msrp": 110,
        "blurb": "Lagavulin 16 — campfire, sea salt, and Islay smoke in a legendary 16-year pour. The Scotch that teaches peat without apology.",
    },
    {
        "sku": "SPI-TRK-GLENFID-12",
        "brand": "Glenfiddich",
        "name": "Glenfiddich 12 Year",
        "expr": "12 Year",
        "type": "Scotch",
        "style": "Single malt Scotch",
        "origin": "Speyside, Scotland",
        "tier": 3,
        "journey": "novice",
        "rank": 8,
        "proof": 80,
        "mash": "100% malted barley",
        "family": "Pear & malt",
        "occasion": "Afternoon pour",
        "pairing": "Mild / Connecticut cigar",
        "notes": "pear, butterscotch, cream, malt, subtle oak, fresh fruit",
        "research": "Glenfiddich official 12 Year Old; 40% ABV Speyside single malt.",
        "source": "Manufacturer official",
        "article": "https://www.glenfiddich.com/12-year-old",
        "best": "First Scotch, mild cigar, user intimidated by peat or smoke.",
        "avoid": "User wants heavy peat or cask-strength intensity.",
        "why": "Recommend as beginner Scotch — pear, honey, and gentle oak without smoke.",
        "msrp": 48,
        "blurb": "Glenfiddich 12 — pear and butterscotch over cream, malt, and subtle oak. Official Speyside first Scotch without peat.",
    },
    {
        "sku": "SPI-TRK-JW-BLUE",
        "brand": "Johnnie Walker",
        "name": "Johnnie Walker Blue Label",
        "expr": "Blue Label",
        "type": "Scotch",
        "style": "Blended Scotch whisky",
        "origin": "Scotland",
        "tier": 7,
        "journey": "advanced",
        "rank": 14,
        "proof": 80,
        "mash": "Blended malts & grains",
        "family": "Silky prestige",
        "occasion": "Celebration",
        "pairing": "Premium cigar",
        "notes": "honey, dark fruit, smoke, hazelnut, chocolate, maritime hint",
        "research": "Prestige bottle — instant recognition even when enthusiasts debate value.",
        "best": "Gift pour, status request, member names Blue Label, lounge demo prestige.",
        "avoid": "User wants single-malt purist only or budget under $50.",
        "why": "Recommend when prestige recognition matters — honeyed blend with smoke and dark fruit, universally known bottle.",
        "msrp": 225,
        "blurb": "Johnnie Walker Blue — instant prestige in the glass. Honey, dark fruit, and a whisper of smoke; value debated, recognition undeniable.",
    },
    {
        "sku": "SPI-TRK-HIBIKI-HARMONY",
        "brand": "Suntory",
        "name": "Hibiki Japanese Harmony",
        "expr": "Harmony",
        "type": "Japanese Whisky",
        "style": "Blended Japanese whisky",
        "origin": "Japan",
        "tier": 6,
        "journey": "intermediate",
        "rank": 15,
        "proof": 86,
        "mash": "Blended malt & grain (Chita, Yamazaki, Hakushu components)",
        "family": "Honey & floral",
        "occasion": "Celebration",
        "pairing": "Medium / refined cigar",
        "notes": "honey, floral, elegant oak, orange peel, white chocolate, sandalwood",
        "research": "Critical for luxury UX — approachable Japanese blend with premium packaging.",
        "best": "Luxury Japanese request, elegant pairing, member wants floral-honey profile.",
        "avoid": "User demands single malt only or heavy peat.",
        "why": "Recommend when the member wants Japanese whisky elegance — honey, floral, and polished oak.",
        "msrp": 95,
        "blurb": "Hibiki Harmony — honey, floral lift, and sandalwood polish. Japanese whisky luxury that photographs as well as it pours.",
    },
    {
        "sku": "SPI-TRK-YAMAZAKI-12",
        "brand": "Suntory",
        "name": "The Yamazaki 12 Year",
        "expr": "12 Year",
        "type": "Japanese Whisky",
        "style": "Single malt Japanese whisky",
        "origin": "Japan",
        "tier": 7,
        "journey": "advanced",
        "rank": 16,
        "proof": 86,
        "mash": "100% malted barley",
        "family": "Fruit & mizunara",
        "occasion": "Collector",
        "pairing": "Refined medium-full cigar",
        "notes": "peach, pineapple, mizunara oak, spice, honey, incense",
        "research": "High recognition single malt; refined pairing bottle when available.",
        "best": "Japanese whisky prestige, collector conversation, refined fruit-oak cigar pairing.",
        "avoid": "Budget-only or user needs everyday $40 pour.",
        "why": "Recommend when Yamazaki name recognition and refined fruit-mizunara pairing are the point.",
        "msrp": 150,
        "blurb": "Yamazaki 12 — peach, mizunara, and quiet spice. The Japanese single malt everyone asks for by name.",
    },
    {
        "sku": "SPI-TRK-DIPLO-RE",
        "brand": "Diplomático",
        "name": "Diplomático Reserva Exclusiva",
        "expr": "Reserva Exclusiva",
        "type": "Rum",
        "style": "Dark rum",
        "origin": "Venezuela",
        "tier": 4,
        "journey": "intermediate",
        "rank": 9,
        "proof": 80,
        "mash": "Sugar cane honey (column + pot still blend)",
        "family": "Sweet & molasses",
        "occasion": "After dinner",
        "pairing": "Maduro / any premium cigar",
        "notes": "orange peel, toffee, licorice, fudge, dark chocolate, dried fruit, molasses",
        "research": "Diplomático official Reserva Exclusiva; 40% ABV Venezuelan rum.",
        "source": "Manufacturer official",
        "article": "https://www.diplomaticorums.com/",
        "best": "Cigar-first pairing, rum curious member, dessert-profile spirit.",
        "avoid": "User wants dry agricole rhum or zero sweetness.",
        "why": "Recommend when cigar pairing is the goal — brown sugar, orange, molasses, and chocolate beside maduro.",
        "msrp": 42,
        "blurb": "Diplomático Reserva Exclusiva — orange peel and toffee over fudge, dark chocolate, and dried fruit. Brand-official cigar-pairing rum.",
    },
    {
        "sku": "SPI-TRK-ZACAPA-23",
        "brand": "Ron Zacapa",
        "name": "Ron Zacapa 23",
        "expr": "23 (solera)",
        "type": "Rum",
        "style": "Premium rum",
        "origin": "Guatemala",
        "tier": 5,
        "journey": "intermediate",
        "rank": 11,
        "proof": 80,
        "mash": "Virgin sugar cane honey",
        "family": "Luxury sweet",
        "occasion": "Celebration",
        "pairing": "Maduro / Connecticut broadleaf",
        "notes": "caramel, vanilla, cacao, butterscotch, toasted hazelnut, toffee, dried pineapple, apricot, nutmeg, leather, tobacco, coffee, cinnamon, ginger",
        "research": "Ron Zacapa official No. 23 Centenario; Sistema Solera 6–23 years; 40% ABV. Rank 11 (rank 10 reserved for Pappy 23).",
        "source": "Manufacturer official",
        "article": "https://www.zacaparum.com/en-us/rums/zacapa-23-centenario",
        "best": "Sweet rum luxury, special occasion cigar, member wants rum without Diplomatico repeat.",
        "avoid": "User wants white rum or dry spirits only.",
        "why": "Recommend when the member wants luxury sweet rum — honey, raisin, and butterscotch beside a premium cigar.",
        "msrp": 55,
        "blurb": "Ron Zacapa 23 — caramel and butterscotch over apricot, nutmeg, leather, and coffee. Solera luxury rum per distillery tasting profile.",
    },
    {
        "sku": "SPI-TRK-HENNESSY-XO",
        "brand": "Hennessy",
        "name": "Hennessy XO",
        "expr": "XO",
        "type": "Cognac",
        "style": "Cognac XO",
        "origin": "Cognac, France",
        "tier": 7,
        "journey": "advanced",
        "rank": 17,
        "proof": 80,
        "mash": "Ugni Blanc wine distillate (blended eaux-de-vie)",
        "family": "Rich & dried fruit",
        "occasion": "Celebration",
        "pairing": "Maduro / robusto cigar",
        "notes": "dried fruit, dark chocolate, oak, spice, leather, candied orange",
        "research": "Mandatory culturally — dominant cognac prestige in US lounges.",
        "best": "Cognac request, hip-hop/lounge culture prestige, after-dinner cigar.",
        "avoid": "User wants unaged spirits or Scotch only.",
        "why": "Recommend when cognac prestige is cultural shorthand — dried fruit, chocolate, and oak depth.",
        "msrp": 200,
        "blurb": "Hennessy XO — the cognac everyone pictures. Dried fruit, dark chocolate, and oak in a bottle built for celebration.",
    },
    {
        "sku": "SPI-TRK-REMY-XO",
        "brand": "Rémy Martin",
        "name": "Rémy Martin XO",
        "expr": "XO",
        "type": "Cognac",
        "style": "Cognac XO (Grande Champagne)",
        "origin": "Cognac, France",
        "tier": 7,
        "journey": "advanced",
        "rank": 18,
        "proof": 80,
        "mash": "Grande Champagne & Petite Champagne eaux-de-vie",
        "family": "Silky fruit",
        "occasion": "After dinner",
        "pairing": "Medium-full / maduro cigar",
        "notes": "fig, jasmine, plum, cinnamon, honey, silky oak",
        "research": "Silky cigar-pairing cognac; fine champagne cognac positioning vs Hennessy.",
        "best": "Member wants elegant cognac for cigar, fruit-forward luxury, Rémy name request.",
        "avoid": "User wants maximum smoke or tequila only.",
        "why": "Recommend when silky cognac beside cigar matters — fig, plum, honey, and fine champagne finesse.",
        "msrp": 190,
        "blurb": "Rémy Martin XO — fig, plum, and jasmine over silky oak. The cognac that whispers luxury beside a maduro instead of shouting it.",
    },
    {
        "sku": "SPI-TRK-CLASE-AZUL-REP",
        "brand": "Clase Azul",
        "name": "Clase Azul Reposado",
        "expr": "Reposado",
        "type": "Tequila",
        "style": "100% agave tequila",
        "origin": "Jalisco, Mexico",
        "tier": 6,
        "journey": "intermediate",
        "rank": 19,
        "proof": 80,
        "mash": "100% Blue Weber agave",
        "family": "Vanilla & sweet agave",
        "occasion": "Celebration",
        "pairing": "Medium cigar",
        "notes": "vanilla, caramel, sweet agave, orange, light pepper, ceramic presentation",
        "research": "Luxury visual bottle — huge recognition in lounge/demo audiences.",
        "best": "Tequila prestige, gift pour, member wants recognizable luxury agave.",
        "avoid": "User wants blanco-only or mezcal smoke.",
        "why": "Recommend when visual luxury and tequila recognition matter — vanilla, caramel, iconic ceramic.",
        "msrp": 150,
        "blurb": "Clase Azul Reposado — vanilla and caramel agave in the ceramic bottle everyone photographs. Luxury tequila as theater.",
    },
    {
        "sku": "SPI-TRK-DJ-1942",
        "brand": "Don Julio",
        "name": "Don Julio 1942",
        "expr": "1942 Añejo",
        "type": "Tequila",
        "style": "100% agave añejo",
        "origin": "Jalisco, Mexico",
        "tier": 6,
        "journey": "intermediate",
        "rank": 20,
        "proof": 80,
        "mash": "100% Blue Weber agave",
        "family": "Caramel & oak",
        "occasion": "Celebration",
        "pairing": "Medium-full cigar",
        "notes": "caramel, vanilla, roasted agave, chocolate, oak, light spice",
        "research": "Users will ask constantly — especially lounge and demo audiences.",
        "best": "Tequila prestige request, 1942 by name, celebratory cigar night.",
        "avoid": "User wants blanco/mezcal smoke or budget under $80.",
        "why": "Recommend when the member names 1942 or wants celebratory tequila — caramel, vanilla, and roasted agave.",
        "msrp": 175,
        "blurb": "Don Julio 1942 — caramel, vanilla, and roasted agave in the pour everyone requests at the lounge. Have an answer ready.",
    },
]


def catalog_line(r: dict) -> str:
    abv = round(r["proof"] * 0.5, 1) if r["proof"] else ""
    j = r["journey"]
    jnote = f" · Journey: {j.capitalize()}" if r["type"] in ("Bourbon", "Rye") else ""
    return (
        f"{r['name']} · {r['origin']} · ${r['msrp']} · {r['proof']} proof ({abv}% ABV){jnote} · "
        f"Notes: {r['notes'].split(',')[0]}, {r['notes'].split(',')[1].strip() if ',' in r['notes'] else ''}"
    ).replace("  ", " ")


def row_array(r: dict) -> list:
    abv = round(r["proof"] * 0.5, 1)
    return [
        r["sku"],
        r["brand"],
        r["name"],
        r["expr"],
        r["type"],
        r["style"],
        r["origin"],
        r["tier"],
        r["journey"],
        r["rank"],
        r["proof"],
        abv,
        r["mash"],
        r["family"],
        r["occasion"],
        r["pairing"],
        r["notes"],
        r["research"],
        r["best"],
        r["avoid"],
        r["why"],
        "High",
        r.get("source", "Product brief + industry reference"),
        r["msrp"],
        catalog_line(r),
        r["blurb"],
        "",
        r.get("article", ""),
        "",
    ]


def main() -> None:
    values = [row_array(r) for r in ROWS]
    payload = {
        "spreadsheetId": "1mLHCA8rvvl5G87FJCxg5tkoDQ1Xp5FDx2QBm7Ty-WUU",
        "range": f"Spirits!A4:AD{3 + len(values)}",
        "valueInputOption": "USER_ENTERED",
        "values": values,
    }
    OUT.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    (BASE / "spirit-research-tracker-batch-1-rows.json").write_text(
        json.dumps([{k: r[k] for k in r} for r in ROWS], indent=2), encoding="utf-8"
    )
    print(f"Wrote {len(values)} rows -> {OUT.name}")


if __name__ == "__main__":
    main()
